#!/usr/bin/env bash
set -euo pipefail

: "${RENDER_JSON:?RENDER_JSON is required}"
: "${BIBATA_SRC:?BIBATA_SRC is required}"
: "${CURSOR_OUT_DIR:?CURSOR_OUT_DIR is required}"
: "${DOCKER_IMAGE_NAME:?DOCKER_IMAGE_NAME is required}"
: "${CURSOR_DEFAULT_SIZE:?CURSOR_DEFAULT_SIZE is required}"

render_json="$(realpath $RENDER_JSON)"

name="$(
    jq -r '
        keys_unsorted
        | if length == 1
          then .[0]
          else error("render json must contain exactly one cursor theme")
          end
    ' "$render_json"
)"

size="$(
    jq -r \
        --arg name "$name" \
        '.[$name].sizes? // empty
         | if type == "array"
           then join(" ")
           else tostring
           end' \
        "$render_json"
)"

if [[ -z "$size" ]]; then
    size="$CURSOR_DEFAULT_SIZE"
fi

comment="Generated by Hyprland theme on $(date -Iseconds)"

echo "[cursor] building $name ($size)"

exec podman run --rm \
    -e SRC=/src \
    -e OUT=/out \
    -e COMMENT="$comment" \
    -e SIZE="$size" \
    -e RENDER_JSON=/render.json \
    -v "$render_json:/render.json:ro" \
    -v "$CURSOR_OUT_DIR:/out" \
    "$DOCKER_IMAGE_NAME"

