-- File: gtk.lua
--
-- Renderer for GTK settings + CSS overrides.
--
-- Output:
--   ~/.config/gtk-3.0/settings.ini
--   ~/.config/gtk-3.0/gtk.css
--   ~/.config/gtk-4.0/settings.ini
--   ~/.config/gtk-4.0/gtk.css

local M = {}

local function shquote(s)
    return "'" .. tostring(s):gsub("'", "'\\''") .. "'"
end

local function dirname(path)
    return tostring(path):match("^(.*)/[^/]+$") or "."
end

local function write_file(path, content)
    os.execute("mkdir -p " .. shquote(dirname(path)))

    local f, err = io.open(path, "w")
    if not f then
        error("failed to open " .. path .. ": " .. tostring(err))
    end

    f:write(content)
    f:close()
end

local function css_color(color)
    if color == nil then
        return "transparent"
    end

    if color == "transparent" then
        return "transparent"
    end

    if color:match("^#") then
        return color
    end

    return "#" .. color
end

local function strip_hash(color)
    return tostring(color):gsub("^#", "")
end

local function hex_to_rgba(color, alpha)
    if color == nil or color == "transparent" then
        return "transparent"
    end

    local hex = strip_hash(color)

    if #hex ~= 6 then
        error("hex_to_rgba expects #rrggbb, got: " .. tostring(color))
    end

    local r = tonumber(hex:sub(1, 2), 16)
    local g = tonumber(hex:sub(3, 4), 16)
    local b = tonumber(hex:sub(5, 6), 16)

    return string.format("rgba(%d, %d, %d, %.3f)", r, g, b, alpha)
end

function M.settings_ini(style)
    local font = style.font
    local icon_theme = style.icons.theme
    local cursor_theme = style.cursor.theme
    local cursor_size = style.cursor.size

    print("style:",style)
    return table.concat({
        "[Settings]",
        "gtk-theme-name=Adwaita-dark",
        "gtk-application-prefer-dark-theme=true",
        "gtk-icon-theme-name=" .. icon_theme,
        "gtk-cursor-theme-name=" .. cursor_theme,
        "gtk-cursor-theme-size=" .. tostring(cursor_size),
        "gtk-font-name=" .. style.font.ui .. " " .. tostring(style.font.size.gtk_pt or style.font.size.ui or 11),
        "gtk-decoration-layout=menu:close",
        "",
    }, "\n")
end

local function render(template, vars)
    return (template:gsub("%${([%w_]+)}", function(key)
        local value = vars[key]

        if value == nil then
            error("missing template variable: " .. key)
        end

        local result = tostring(value)

        if (result:match("%${")) then
            error("Not all variables replaced")
        end

        return result
    end))
end

function M.css(style)
    local c = style.color
    local metric = style.metric
    local radius = metric.border.radius or 7

     local v = {
        name = tostring(style.name),

        bg = css_color(c.bg),
        fg = css_color(c.fg),
        surface = css_color(c.surface),
        surface_alt = css_color(c.surface_alt),

        bg_soft = css_color(c.bg_soft or c.bg),

        accent = css_color(c.accent),
        accent_alt = css_color(c.accent_alt or c.accent),

        border = css_color(c.border),
        border_sub = css_color(c.border_subtle or c.border),

        warning = css_color(c.warning),
        danger = css_color(c.danger),
        success = css_color(c.positive),

        muted = css_color(c.muted),
        fg_strong = css_color(c.fg_strong or c.fg),

        hover_bg = css_color(c.hover_bg),
        active_bg = css_color(c.active_bg),

        tooltip_bg = hex_to_rgba(c.bg, 0.98),

        radius = radius,
    }
return render([[

/*
 * Generated by ~/.config/hypr/gtk.lua
 * Style: ${name}
 */

@define-color theme_bg_color ${bg};
@define-color theme_fg_color ${fg};
@define-color theme_base_color ${surface};
@define-color theme_text_color ${fg};

@define-color theme_selected_bg_color ${accent};
@define-color theme_selected_fg_color ${bg};

@define-color borders ${border};
@define-color warning_color ${warning};
@define-color error_color ${danger};
@define-color success_color ${success};

* {
    outline-color: ${accent};
    caret-color: ${accent};
}

window,
dialog,
popover,
.background {
    background-color: ${bg};
    color: ${fg};
}

button {
    color: ${fg};
    background-color: ${surface};
    border: 1px solid ${border};
    border-radius: ${radius}px;
}

/* notebook */
notebook > header {
    background-color: ${bg};
    border-color: ${border_sub};
}

notebook > header > tabs > tab {
    color: ${muted};
    background-color: ${surface};
    box-shadow: inset 0 -2px transparent;
}

notebook > header > tabs > tab:hover {
    color: ${fg_strong};
    box-shadow: inset 0 -2px ${accent};
}

notebook > header > tabs > tab:checked {
    color: ${fg_strong};
    background-color: ${active_bg};
    box-shadow: inset 0 -2px ${accent};
}

scrollbar slider {
    background-color: ${surface_alt};
    border-radius: ${radius}px;
}

scrollbar slider:hover {
    background-color: ${accent_alt};
}

tooltip {
    color: ${fg};
    background-color: ${tooltip_bg};
    border: 1px solid ${accent};
    border-radius: ${radius}px;
}

]], v)

--     return string.format([[
-- /*
--  * Generated by ~/.config/hypr/gtk.lua
--  * Style: %s
--  *
--  * This is a GTK override, not a full GTK theme.
--  */
-- 
-- @define-color theme_bg_color %s;
-- @define-color theme_fg_color %s;
-- @define-color theme_base_color %s;
-- @define-color theme_text_color %s;
-- 
-- @define-color theme_selected_bg_color %s;
-- @define-color theme_selected_fg_color %s;
-- 
-- @define-color borders %s;
-- @define-color warning_color %s;
-- @define-color error_color %s;
-- @define-color success_color %s;
-- 
-- * {
--     outline-color: %s;
--     caret-color: %s;
-- }
-- 
-- window,
-- dialog,
-- popover,
-- .background {
--     background-color: %s;
--     color: %s;
-- }
-- 
-- headerbar,
-- .titlebar,
-- toolbar,
-- menubar {
--     background-color: %s;
--     color: %s;
--     border-color: %s;
-- }
-- 
-- button {
--     color: %s;
--     background-color: %s;
--     border: 1px solid %s;
--     border-radius: %dpx;
--     padding: 5px 9px;
--     background-image: none;
--     box-shadow: none;
--     text-shadow: none;
-- }
-- 
-- button:hover {
--     color: %s;
--     background-color: %s;
--     border-color: %s;
-- }
-- 
-- button:checked,
-- button:active {
--     color: %s;
--     background-color: %s;
--     border-color: %s;
-- }
-- 
-- entry,
-- spinbutton,
-- combobox box,
-- textview,
-- treeview,
-- list,
-- .content-view {
--     color: %s;
--     background-color: %s;
--     border-color: %s;
--     border-radius: %dpx;
-- }
-- 
-- entry:focus,
-- spinbutton:focus,
-- textview:focus {
--     border-color: %s;
-- }
-- 
-- selection,
-- *:selected {
--     color: %s;
--     background-color: %s;
-- }
-- 
-- menu,
-- menuitem,
-- popover {
--     color: %s;
--     background-color: %s;
-- }
-- 
-- menuitem:hover {
--     color: %s;
--     background-color: %s;
-- }
-- 
-- notebook tab {
--     color: %s;
--     background-color: %s;
--     border-color: %s;
--     padding: 5px 9px;
-- }
-- 
-- notebook tab:checked {
--     color: %s;
--     background-color: %s;
--     border-color: %s;
-- }
-- 
-- /* Force notebook underline + stack switchers to Gruvbox accent */
-- notebook > header,
-- notebook > header.top,
-- notebook > header.bottom,
-- notebook > header.left,
-- notebook > header.right {
--     background-color: %s;
--     border-color: %s;
-- }
-- 
-- /* remove Adwaita's underline */
-- notebook > header > tabs > tab {
--     color: %s;
--     background-color: %s;
--     border: none;
--     box-shadow: inset 0 -2px transparent;
-- }
-- 
-- notebook > header > tabs > tab:hover {
--     color: %s;
--     box-shadow: inset 0 -2px %s;
-- }
-- 
-- notebook > header > tabs > tab:checked {
--     color: %s;
--     background-color: %s;
--     box-shadow: inset 0 -2px %s;
-- }
-- 
-- /* GTK4 stack switchers / segmented tabs */
-- stackswitcher button:checked,
-- stacksidebar row:selected {
--     background-color: %s;
--     color: %s;
-- }
-- 
-- scrollbar slider {
--     background-color: %s;
--     border-radius: %dpx;
-- }
-- 
-- scrollbar slider:hover {
--     background-color: %s;
-- }
-- 
-- tooltip {
--     color: %s;
--     background-color: %s;
--     border: 1px solid %s;
--     border-radius: %dpx;
-- }
-- 
-- tooltip label {
--     color: %s;
-- }
-- ]],
--         tostring(style.name),
-- 
--         css_color(c.bg),
--         css_color(c.fg),
--         css_color(c.surface),
--         css_color(c.fg),
-- 
--         css_color(c.accent),
--         css_color(c.bg),
-- 
--         css_color(c.border),
--         css_color(c.warning),
--         css_color(c.danger),
--         css_color(c.positive),
-- 
--         css_color(c.accent),
--         css_color(c.accent),
-- 
--         css_color(c.bg),
--         css_color(c.fg),
-- 
--         css_color(c.surface),
--         css_color(c.fg),
--         css_color(c.border_subtle or c.border),
-- 
--         css_color(c.fg),
--         css_color(c.surface),
--         css_color(c.border),
--         radius,
-- 
--         css_color(c.fg_strong or c.fg),
--         css_color(c.hover_bg),
--         css_color(c.accent),
-- 
--         css_color(c.bg),
--         css_color(c.accent),
--         css_color(c.accent_alt or c.accent),
-- 
--         css_color(c.fg),
--         css_color(c.bg_soft or c.bg),
--         css_color(c.border),
--         radius,
-- 
--         css_color(c.accent),
-- 
--         css_color(c.bg),
--         css_color(c.accent),
-- 
--         css_color(c.fg),
--         css_color(c.surface),
-- 
--         css_color(c.bg),
--         css_color(c.accent),
-- 
--         css_color(c.muted),
--         css_color(c.surface),
--         css_color(c.border_subtle or c.border),
-- 
--         css_color(c.fg_strong or c.fg),
--         css_color(c.active_bg),
--         css_color(c.accent),
-- 
--         css_color(c.surface_alt),
--         radius,
-- 
--         css_color(c.accent_alt or c.accent),
-- 
--         css_color(c.fg),
--         hex_to_rgba(c.bg, 0.98),
--         css_color(c.accent),
--         radius,
-- 
--         css_color(c.fg)
--     )
end

function M.write(style)
    local home = os.getenv("HOME")

    write_file(home .. "/.config/gtk-3.0/settings.ini", M.settings_ini(style))
    write_file(home .. "/.config/gtk-3.0/gtk.css", M.css(style))

    write_file(home .. "/.config/gtk-4.0/settings.ini", M.settings_ini(style))
    write_file(home .. "/.config/gtk-4.0/gtk.css", M.css(style))
end

return M
