-- File: hyprlock.lua
--
-- Renderer for ~/.config/hypr/hyprlock.conf

local M = {}

local function shquote(s)
    return "'" .. tostring(s):gsub("'", "'\\''") .. "'"
end

local function dirname(path)
    return tostring(path):match("^(.*)/[^/]+$") or "."
end

local function write_file(path, content)
    os.execute("mkdir -p " .. shquote(dirname(path)))

    local f, err = io.open(path, "w")
    if not f then
        error("failed to open " .. path .. ": " .. tostring(err))
    end

    f:write(content)
    f:close()
end

local function strip_hash(color)
    return tostring(color):gsub("^#", "")
end

local function rgba(color, alpha)
    local hex = strip_hash(color)

    if #hex == 8 then
        return "rgba(" .. hex .. ")"
    end

    if #hex ~= 6 then
        error("hyprlock color expects #rrggbb or #rrggbbaa, got: " .. tostring(color))
    end

    alpha = alpha or 1.0
    local aa = math.floor(alpha * 255 + 0.5)
    return string.format("rgba(%s%02x)", hex, aa)
end

local function font_family(style)
    return style.font.ui or "sans"
end

function M.conf(style, opts)
    opts = opts or {}

    local c = style.color
    local comp = style.component or {}
    local win = comp.window or {}
    local metric = style.metric or {}

    local radius =
        (metric.border and metric.border.radius)
        or win.radius
        or 8

    local border_width =
        (metric.border and metric.border.width)
        or (win.border and win.border.width)
        or 1

    local wallpaper = opts.wallpaper or ""
    local bg_path = wallpaper ~= "" and wallpaper or ""

    local bg_block
    if bg_path ~= "" then
        bg_block = table.concat({
            "background {",
            "    monitor =",
            "    path = " .. bg_path,
            "    color = " .. rgba(c.bg, 1.0),
            "    blur_passes = 2",
            "    blur_size = 6",
            "    noise = 0.0117",
            "    contrast = 0.90",
            "    brightness = 0.72",
            "    vibrancy = 0.12",
            "    vibrancy_darkness = 0.05",
            "}",
        }, "\n")
    else
        bg_block = table.concat({
            "background {",
            "    monitor =",
            "    color = " .. rgba(c.bg, 1.0),
            "}",
        }, "\n")
    end

    return table.concat({
        "# Generated by ~/.config/hypr/hyprlock.lua",
        "# Style: " .. tostring(style.name),
        "",
        "general {",
        "    hide_cursor = true",
        "    ignore_empty_input = true",
        "    immediate_render = true",
        "    text_trim = true",
        "}",
        "",
        "animations {",
        "    enabled = true",
        "}",
        "",
        bg_block,
        "",
        "label {",
        "    monitor =",
        "    text = $TIME",
        "    color = " .. rgba(c.fg_strong or c.fg, 1.0),
        "    font_size = 72",
        "    font_family = " .. font_family(style),
        "    halign = center",
        "    valign = center",
        "    position = 0, -110",
        "    shadow_passes = 2",
        "    shadow_size = 3",
        "    shadow_color = " .. rgba(c.bg, 0.65),
        "}",
        "",
        "label {",
        "    monitor =",
        "    text = cmd[update:1000] date +'%A, %x'",
        "    color = " .. rgba(c.muted or c.fg_soft, 1.0),
        "    font_size = 18",
        "    font_family = " .. font_family(style),
        "    halign = center",
        "    valign = center",
        "    position = 0, -50",
        "    shadow_passes = 2",
        "    shadow_size = 3",
        "    shadow_color = " .. rgba(c.bg, 0.65),
        "}",
        "",
        "input-field {",
        "    monitor =",
        "    size = 280, 48",
        "    outline_thickness = " .. tostring(border_width),
        "    dots_size = 0.22",
        "    dots_spacing = 0.18",
        "    dots_center = false",
        "    fade_on_empty = true",
        "    placeholder_text = Password",
        "    hide_input = false",
        "    rounding = " .. tostring(radius),
        "    outer_color = " .. rgba(c.accent, 1.0),
        "    inner_color = " .. rgba(c.surface or c.bg, 0.88),
        "    font_color = " .. rgba(c.fg, 1.0),
        "    fail_color = " .. rgba(c.danger, 1.0),
        "    check_color = " .. rgba(c.warning, 1.0),
        "    capslock_color = " .. rgba(c.warning, 1.0),
        "    position = 0, 85",
        "    halign = center",
        "    valign = center",
        "}",
        "",
        "label {",
        "    monitor =",
        "    text = $FAIL",
        "    color = " .. rgba(c.danger, 1.0),
        "    font_size = 14",
        "    font_family = " .. font_family(style),
        "    halign = center",
        "    valign = center",
        "    position = 0, 88",
        "}",
        "",
        "label {",
        "    monitor =",
        "    text = $USER",
        "    color = " .. rgba(c.muted or c.fg_soft, 1.0),
        "    font_size = 14",
        "    font_family = " .. font_family(style),
        "    halign = center",
        "    valign = bottom",
        "    position = 0, 150",
        "}",
        "",
    }, "\n")
end

function M.write(style, opts, path)
    path = path or (os.getenv("HOME") .. "/.config/hypr/hyprlock.conf")
    write_file(path, M.conf(style, opts))
end

return M

