-- File: hyprtoolkit.lua
--
-- Renderer for ~/.config/hypr/hyprtoolkit.conf
--
-- Input:
--   style table from base.lua / green_teal.lua / orange_yellow.lua / blue_aqua.lua
--
-- Output:
--   ~/.config/hypr/hyprtoolkit.conf

local M = {}

local function shquote(s)
    return "'" .. tostring(s):gsub("'", "'\\''") .. "'"
end

local function dirname(path)
    return tostring(path):match("^(.*)/[^/]+$") or "."
end

local function strip_hash(color)
    return tostring(color):gsub("^#", "")
end

local function toolkit_color(color)
    local hex = strip_hash(color)

    if #hex == 6 then
        return "0xFF" .. hex
    end

    if #hex == 8 then
        -- Accept #RRGGBBAA and convert to 0xAARRGGBB.
        local rrggbb = hex:sub(1, 6)
        local aa = hex:sub(7, 8)
        return "0x" .. aa .. rrggbb
    end

    error("hyprtoolkit color expects #rrggbb or #rrggbbaa, got: " .. tostring(color))
end

local function write_file(path, content)
    os.execute("mkdir -p " .. shquote(dirname(path)))

    local f, err = io.open(path, "w")
    if not f then
        error("failed to open " .. path .. ": " .. tostring(err))
    end

    f:write(content)
    f:close()
end

function M.conf(style)
    local c = style.color
    local font = style.font
    local metric = style.metric or {}

    local font_size =
        font.size.ui
        or font.size.bar
        or 14

    local small_font_size =
        font.size.small
        or math.max(font_size - 2, 9)

    local h3_size =
        font.size.h3
        or math.max(font_size, 13)

    local h2_size =
        font.size.h2
        or h3_size + 2

    local h1_size =
        font.size.h1
        or h2_size + 4

    local rounding_small =
        metric.border and metric.border.radius or 5

    local rounding_large =
        rounding_small + 5

    local icon_theme =
        style.icon_theme
        or style.icon_theme_name
        or ""

    return table.concat({
        "# Generated by ~/.config/hypr/hyprtoolkit.lua",
        "# Style: " .. tostring(style.name),
        "",
        "background = " .. toolkit_color(c.bg),
        "base = " .. toolkit_color(c.surface or c.bg),
        "alternate_base = " .. toolkit_color(c.surface_alt or c.surface or c.bg),
        "text = " .. toolkit_color(c.fg),
        "bright_text = " .. toolkit_color(c.fg_strong or c.fg),
        "accent = " .. toolkit_color(c.accent),
        "accent_secondary = " .. toolkit_color(c.accent_alt or c.accent),
        "",
        "h1_size = " .. tostring(h1_size),
        "h2_size = " .. tostring(h2_size),
        "h3_size = " .. tostring(h3_size),
        "font_size = " .. tostring(font_size),
        "small_font_size = " .. tostring(small_font_size),
        "",
        "font_family = " .. tostring(font.ui),
        "font_family_monospace = " .. tostring(font.mono),
        "icon_theme = " .. tostring(icon_theme),
        "",
        "rounding_large = " .. tostring(rounding_large),
        "rounding_small = " .. tostring(rounding_small),
        "",
    }, "\n")
end

function M.write(style, path)
    path = path or (os.getenv("HOME") .. "/.config/hypr/hyprtoolkit.conf")
    write_file(path, M.conf(style))
end
return M
