-- File: mako.lua
--
-- Renderer for ~/.config/mako/config
--
-- Input:
--   style table from base.lua / green_teal.lua / orange_yellow.lua / blue_aqua.lua

local M = {}

local function shquote(s)
    return "'" .. tostring(s):gsub("'", "'\\''") .. "'"
end

local function dirname(path)
    return tostring(path):match("^(.*)/[^/]+$") or "."
end

local function write_file(path, content)
    os.execute("mkdir -p " .. shquote(dirname(path)))

    local f, err = io.open(path, "w")
    if not f then
        error("failed to open " .. path .. ": " .. tostring(err))
    end

    f:write(content)
    f:close()
end

local function strip_hash(color)
    return tostring(color):gsub("^#", "")
end

local function mako_color(color, alpha)
    local hex = strip_hash(color)

    if #hex == 8 then
        return "#" .. hex
    end

    if #hex ~= 6 then
        error("mako color expects #rrggbb or #rrggbbaa, got: " .. tostring(color))
    end

    alpha = alpha or 1.0
    local aa = math.floor(alpha * 255 + 0.5)

    return string.format("#%s%02x", hex, aa)
end

function M.config(style)
    local c = style.color
    local font = style.font
    local metric = style.metric or {}

    local radius =
        metric.border and metric.border.radius
        or 7

    local border_width =
        metric.border and metric.border.width
        or 1

    local font_size =
        font.size.ui
        or font.size.bar
        or 14

    return table.concat({
        "# Generated by ~/.config/hypr/mako.lua",
        "# Style: " .. tostring(style.name),
        "",
        "font=" .. font.ui .. " " .. tostring(font_size),
        "",
        "background-color=" .. mako_color(c.surface or c.bg, 0.96),
        "text-color=" .. mako_color(c.fg, 1.0),
        "border-color=" .. mako_color(c.accent, 1.0),
        "progress-color=over " .. mako_color(c.accent_alt or c.accent, 1.0),
        "",
        "border-size=" .. tostring(border_width),
        "border-radius=" .. tostring(radius),
        "",
        "padding=10",
        "margin=12",
        "width=360",
        "height=120",
        "",
        "default-timeout=6000",
        "ignore-timeout=0",
        "",
        "anchor=top-right",
        "layer=overlay",
        "",
        "icons=1",
        "max-icon-size=48",
        "",
        "markup=1",
        "actions=1",
        "history=1",
        "",
        "[urgency=low]",
        "border-color=" .. mako_color(c.border or c.surface_alt, 1.0),
        "default-timeout=3500",
        "",
        "[urgency=normal]",
        "border-color=" .. mako_color(c.accent, 1.0),
        "",
        "[urgency=high]",
        "border-color=" .. mako_color(c.danger, 1.0),
        "background-color=" .. mako_color(c.surface or c.bg, 0.98),
        "text-color=" .. mako_color(c.fg_strong or c.fg, 1.0),
        "default-timeout=0",
        "",
    }, "\n")
end

function M.write(style, path)
    path = path or (os.getenv("HOME") .. "/.config/mako/config")
    write_file(path, M.config(style))
end

return M
