# Monitor Configuration: Look at https://wiki.hypr.land/Configuring/Monitors/
# List all monitors: hyprctl monitors
monitorv2 {
	output = desc:Dell Inc. DELL S2725DC 48KTQC4
	mode = 2560x1440@143.97Hz
	position = 0x0
	scale = 1
	vrr = 1 # 0=off, 1=on, 2=fullscreen only
}

# This old TV has some modeline issues
# Add reserved space to the left
monitorv2 {
	output = desc:Panasonic Industry Company PanasonicTV1
	mode = preferred
	addreserved = 0, 0, 20, 0 # top, bottom, left, right
}

