-- File: nwgbar.lua
--
-- Renderer for nwg-launchers/nwgbar GTK CSS.
-- Input:  style table from base.lua / green_teal.lua / orange_yellow.lua / blue_aqua.lua
-- Output: ~/.config/nwg-launchers/nwgbar/style.css

local M = {}

local function strip_hash(color)
    return tostring(color):gsub("^#", "")
end

local function css_color(color)
    if color == nil then
        return "transparent"
    end

    if color == "transparent" then
        return "transparent"
    end

    if color:match("^#") then
        return color
    end

    return "#" .. color
end

local function hex_to_rgba(color, alpha)
    if color == nil or color == "transparent" then
        return "transparent"
    end

    local hex = strip_hash(color)

    if #hex ~= 6 then
        error("hex_to_rgba expects #rrggbb, got: " .. tostring(color))
    end

    local r = tonumber(hex:sub(1, 2), 16)
    local g = tonumber(hex:sub(3, 4), 16)
    local b = tonumber(hex:sub(5, 6), 16)

    return string.format("rgba(%d, %d, %d, %.3f)", r, g, b, alpha)
end

local function q(s)
    return '"' .. tostring(s):gsub('"', '\\"') .. '"'
end

local function ensure_parent_dir(path)
    local dir = path:match("^(.*)/[^/]+$")
    if dir and dir ~= "" then
        os.execute("mkdir -p " .. q(dir))
    end
end

function M.css(style)
    local c = style.color
    local font = style.font
    local metric = style.metric
    local comp = style.component

    local win = comp.window
    local bar = comp.bar
    local tooltip = comp.tooltip

    local radius = math.max(metric.border.radius + 5, 10)
    local button_radius = math.max(metric.border.radius + 7, 12)

    local ui_font = font.ui
    local icon_font = font.icon or font.mono
    local label_size = font.size.ui or font.size.bar
    local icon_size = font.size.icon or (font.size.bar + 4)

    return string.format([[
/*
 * Generated by ~/.config/hypr/nwgbar.lua
 * Style: %s
 *
 * GTK CSS for nwg-launchers/nwgbar.
 */

* {
    font-family: %s, %s, sans-serif;
    font-size: %dpx;
    color: %s;
}

window {
    background: %s;
    border-radius: %dpx;
}

button {
    color: %s;
    background: %s;

    border: %dpx solid %s;
    border-radius: %dpx;

    margin: 8px;
    padding: 14px 18px;

    min-width: 104px;
    min-height: 92px;

    background-image: none;
    box-shadow: none;
    text-shadow: none;
}

button:hover {
    color: %s;
    background: %s;
    border-color: %s;
}

button:focus {
    color: %s;
    background: %s;
    border-color: %s;
    outline-style: none;
}

button:active {
    color: %s;
    background: %s;
    border-color: %s;
}

button label {
    color: inherit;
    font-family: %s, sans-serif;
    font-size: %dpx;
    font-weight: 500;

    margin-top: 6px;
}

button image {
    color: inherit;
    -gtk-icon-shadow: none;
}

/*
 * If nwgbar renders symbolic icons through GTK,
 * this helps keep them visually aligned with the flavor.
 */
image {
    color: %s;
}

/*
 * Tooltips, if GTK shows them.
 */
tooltip {
    color: %s;
    background: %s;
    border: %dpx solid %s;
    border-radius: %dpx;
}

tooltip label {
    color: %s;
}
]],
        style.name,

        q(ui_font),
        q(icon_font),
        label_size,
        css_color(c.fg),

        hex_to_rgba(bar.bg or c.bg, 0.88),
        radius,

        css_color(c.fg),
        css_color(bar.module.bg or c.surface),
        metric.border.width,
        css_color(c.border_subtle or c.border),
        button_radius,

        css_color(c.fg_strong),
        css_color(c.hover_bg),
        css_color(c.accent),

        css_color(c.fg_strong),
        css_color(c.active_bg),
        css_color(c.accent_alt or c.accent),

        css_color(c.bg),
        css_color(c.accent),
        css_color(c.accent_alt or c.accent),

        q(ui_font),
        label_size,

        css_color(c.accent),

        css_color(tooltip.fg),
        hex_to_rgba(tooltip.bg, style.opacity.tooltip or 0.98),
        metric.border.width,
        css_color(tooltip.border),
        tooltip.radius,

        css_color(tooltip.fg)
    )
end

function M.write(style, path)
    path = path or (os.getenv("HOME") .. "/.config/nwg-launchers/nwgbar/style.css")

    ensure_parent_dir(path)

    local f, err = io.open(path, "w")
    if not f then
        error("failed to open nwgbar CSS output: " .. tostring(err))
    end

    f:write(M.css(style))
    f:close()
end

return M

