-- File: shell.lua
--
-- Renderer for shell ANSI/OSC terminal colors.
--
-- Output:
--   ~/.config/hypr/generated/shell-theme.sh
--
-- Also patches:
--   ~/.bashrc or ~/.zshrc
--
-- This targets interactive shell startup. It does not replace a proper
-- Kitty theme file; it sets palette colors dynamically via OSC sequences.

local M = {}

local MARK_BEGIN = "# >>> hyprland generated shell theme >>>"
local MARK_END   = "# <<< hyprland generated shell theme <<<"

local function shquote(s)
    return "'" .. tostring(s):gsub("'", "'\\''") .. "'"
end

local function dirname(path)
    return tostring(path):match("^(.*)/[^/]+$") or "."
end

local function basename(path)
    return tostring(path):match("([^/]+)$") or tostring(path)
end

local function write_file(path, content)
    os.execute("mkdir -p " .. shquote(dirname(path)))

    local f, err = io.open(path, "w")
    if not f then
        error("failed to open " .. path .. ": " .. tostring(err))
    end

    f:write(content)
    f:close()
end

local function read_file(path)
    local f = io.open(path, "r")
    if not f then
        return ""
    end

    local content = f:read("*a") or ""
    f:close()
    return content
end

local function strip_hash(color)
    return tostring(color):gsub("^#", "")
end

local function css_color(color)
    if color == nil then
        error("nil color")
    end

    if color:match("^#") then
        return color
    end

    return "#" .. color
end

local function shell_name(shell)
    local s = basename(shell or os.getenv("SHELL") or "")
    if s == "" then
        return "sh"
    end
    return s
end

local function rc_path(shell)
    local home = os.getenv("HOME")
    local s = shell_name(shell)

    if s == "bash" then
        return home .. "/.bashrc"
    end

    if s == "zsh" then
        return home .. "/.zshrc"
    end

    error("unsupported shell for theme injection: " .. tostring(shell))
end

local function managed_block(theme_path)
    return table.concat({
        MARK_BEGIN,
        "[ -r " .. shquote(theme_path) .. " ] && . " .. shquote(theme_path),
        MARK_END,
        "",
    }, "\n")
end

local function patch_rc(path, theme_path)
    local old = read_file(path)
    local block = managed_block(theme_path)

    local pattern =
        MARK_BEGIN:gsub("([^%w])", "%%%1")
        .. ".-"
        .. MARK_END:gsub("([^%w])", "%%%1")
        .. "\n?"

    local new, n = old:gsub(pattern, block)

    if n == 0 then
        if #new > 0 and not new:match("\n$") then
            new = new .. "\n"
        end
        new = new .. "\n" .. block
    end

    write_file(path, new)
end

local function ansi_palette(style)
    local c = style.palette or style.color

    return {
        -- normal
        [0]  = c.dark0_hard or style.color.bg_hard or style.color.bg,
        [1]  = c.red or style.color.danger,
        [2]  = c.green or style.color.positive,
        [3]  = c.yellow or style.color.warning,
        [4]  = c.blue or style.color.info,
        [5]  = c.purple or style.color.accent,
        [6]  = c.aqua or style.color.accent_alt,
        [7]  = c.light1 or style.color.fg,

        -- bright
        [8]  = c.gray or style.color.disabled,
        [9]  = c.bright_red or style.color.danger,
        [10] = c.bright_green or style.color.positive,
        [11] = c.bright_yellow or style.color.warning,
        [12] = c.bright_blue or style.color.info,
        [13] = c.bright_purple or style.color.accent,
        [14] = c.bright_aqua or style.color.accent_alt,
        [15] = c.light0 or style.color.fg_strong or style.color.fg,
    }
end

function M.script(style)
    local c = style.color
    local pal = ansi_palette(style)

    local lines = {
        "#!/usr/bin/env sh",
        "# Generated by ~/.config/hypr/shell.lua",
        "# Style: " .. tostring(style.name),
        "",
        "# Only apply in interactive terminals.",
        "case \"$-\" in",
        "  *i*) ;;",
        "  *) return 0 2>/dev/null || exit 0 ;;",
        "esac",
        "",
        "# OSC helper. ST terminator is ESC backslash.",
        "osc() { printf '\\033]%s\\033\\\\' \"$1\"; }",
        "",
        "# Terminal foreground, background, cursor.",
        "osc '10;" .. css_color(c.fg) .. "'",
        "osc '11;" .. css_color(c.bg) .. "'",
        "osc '12;" .. css_color(c.accent or c.fg) .. "'",
        "",
        "# ANSI palette.",
    }

    for i = 0, 15 do
        table.insert(lines, "osc '4;" .. tostring(i) .. ";" .. css_color(pal[i]) .. "'")
    end

    table.insert(lines, "")
    table.insert(lines, "# Optional readline/fzf-ish defaults for tools that honor env colors.")
    table.insert(lines, "export FZF_DEFAULT_OPTS=${FZF_DEFAULT_OPTS:-'--color=fg:" .. css_color(c.fg) ..
        ",bg:" .. css_color(c.bg) ..
        ",hl:" .. css_color(c.accent) ..
        ",fg+:" .. css_color(c.fg_strong or c.fg) ..
        ",bg+:" .. css_color(c.surface or c.bg) ..
        ",hl+:" .. css_color(c.accent_alt or c.accent) ..
        ",info:" .. css_color(c.muted) ..
        ",prompt:" .. css_color(c.accent) ..
        ",pointer:" .. css_color(c.accent_alt or c.accent) ..
        ",marker:" .. css_color(c.positive) ..
        "'}")

    table.insert(lines, "")

    return table.concat(lines, "\n")
end

function M.write(style, shell, opts)
    opts = opts or {}

    local home = os.getenv("HOME")
    local theme_path =
        opts.theme_path
        or (home .. "/.config/hypr/generated/shell-theme.sh")

    write_file(theme_path, M.script(style))
    os.execute("chmod +x " .. shquote(theme_path))

    local rc = opts.rc_path or rc_path(shell)
    patch_rc(rc, theme_path)

    return {
        theme_path = theme_path,
        rc_path = rc,
    }
end

return M
