-- File: waybar.lua
--
-- Renderer for Waybar style.css.
-- Input:  style table from base.lua / green_teal.lua
-- Output: ~/.config/waybar/style.css
--
-- This file is code. The style files remain pure data.

local M = {}

local function strip_hash(color)
    return tostring(color):gsub("^#", "")
end

local function css_color(color)
    if color == nil then
        return "transparent"
    end

    if color == "transparent" then
        return "transparent"
    end

    if color:match("^#") then
        return color
    end

    return "#" .. color
end

local function hex_to_rgba(color, alpha)
    if color == nil or color == "transparent" then
        return "transparent"
    end

    local hex = strip_hash(color)

    if #hex ~= 6 then
        error("hex_to_rgba expects #rrggbb, got: " .. tostring(color))
    end

    local r = tonumber(hex:sub(1, 2), 16)
    local g = tonumber(hex:sub(3, 4), 16)
    local b = tonumber(hex:sub(5, 6), 16)

    return string.format("rgba(%d, %d, %d, %.3f)", r, g, b, alpha)
end

local function q(s)
    return '"' .. tostring(s):gsub('"', '\\"') .. '"'
end

function M.css(style)
    local c = style.color
    local font = style.font
    local comp = style.component
    local bar = comp.bar
    local mod = bar.module
    local ws = comp.workspace
    local tooltip = comp.tooltip

    return string.format([[
/*
 * Generated by ~/.config/hypr/waybar.lua
 * Style: %s
 *
 * Do not hand-edit this file unless you enjoy losing arguments
 * against your own future self.
 */

* {
    border: none;
    min-height: 0;
    font-family: %s, %s, sans-serif;
    font-size: %dpx;
}

window#waybar {
    color: %s;
    background: %s;
}

/* Remove Waybar's default hover weirdness. */
#workspaces button:hover {
    background: %s;
    box-shadow: none;
    text-shadow: none;
}

/* Shared module capsule style. */
#workspaces,
#window,
#clock,
#battery,
#cpu,
#memory,
#disk,
#temperature,
#backlight,
#network,
#pulseaudio,
#wireplumber,
#tray,
#idle_inhibitor,
#custom-media,
#custom-power,
#custom-notification,
#custom-updates {
    color: %s;
    background: %s;
    border-radius: %dpx;
    padding: %dpx %dpx;
    margin: %dpx %dpx;
}

/* Workspaces are a capsule containing smaller pills. */
#workspaces {
    padding: %dpx %dpx;
}

#workspaces button {
    color: %s;
    background: %s;
    border-radius: %dpx;
    padding: 0 %dpx;
    margin: 0 1px;
}

#workspaces button.empty {
    color: %s;
}

#workspaces button.persistent {
    color: %s;
}

#workspaces button.visible {
    color: %s;
    background: %s;
}

#workspaces button.active {
    color: %s;
    background: %s;
}

#workspaces button.special {
    color: %s;
    background: %s;
}

#workspaces button.urgent {
    color: %s;
    background: %s;
}

/* Current focused window title. */
#window {
    color: %s;
    font-weight: 700;
}

/* Common status modules. */
#clock {
    color: %s;
}

#battery {
    color: %s;
}

#battery.charging,
#battery.plugged {
    color: %s;
}

#battery.warning:not(.charging) {
    color: %s;
    background: %s;
}

#battery.critical:not(.charging) {
    color: %s;
    background: %s;
}

#network.disconnected,
#pulseaudio.muted,
#wireplumber.muted {
    color: %s;
}

#tray {
    padding-top: 0;
    padding-bottom: 0;
    padding-left: %dpx;
    padding-right: %dpx;
}

#custom-launcher,
#custom-apps {
    font-size: 17px;
    padding-left: 7px;
    padding-right: 7px;
}

tooltip {
    color: %s;
    background: %s;
    border: %dpx solid %s;
    border-radius: %dpx;
}

tooltip label {
    color: %s;
}
]],
        style.name,

        q(font.ui),
        q(font.mono),
        font.size.bar,

        css_color(bar.fg),
        hex_to_rgba(bar.bg, bar.opacity),

        css_color(c.hover_bg),

        css_color(mod.fg),
        css_color(mod.bg),
        mod.radius,
        mod.padding_y,
        mod.padding_x,
        mod.margin_y,
        mod.margin_x,

        mod.padding_y,
        mod.padding_x,

        css_color(ws.fg),
        css_color(ws.bg),
        ws.radius,
        ws.padding_x,

        css_color(ws.fg_empty),
        css_color(ws.fg),
        css_color(ws.fg_visible),
        css_color(ws.bg_visible or ws.bg),

        css_color(ws.fg_active),
        css_color(ws.bg_active),

        css_color(ws.fg_special or ws.fg_visible),
        css_color(ws.bg_special or ws.bg),

        css_color(c.bg),
        css_color(ws.bg_urgent),

        css_color(c.fg_soft),

        css_color(c.accent),
        css_color(c.fg),

        css_color(c.positive),

        css_color(c.bg),
        css_color(c.warning),

        css_color(c.bg),
        css_color(c.danger),

        css_color(c.disabled),

        mod.padding_x,
        mod.padding_x,

        css_color(tooltip.fg),
        hex_to_rgba(tooltip.bg, style.opacity.tooltip),
        style.metric.border.width,
        css_color(tooltip.border),
        tooltip.radius,

        css_color(tooltip.fg)
    )
end

function M.write(style, path)
    path = path or (os.getenv("HOME") .. "/.config/waybar/style.css")

    local f, err = io.open(path, "w")
    if not f then
        error("failed to open Waybar CSS output: " .. tostring(err))
    end

    f:write(M.css(style))
    f:close()
end

return M
