# If only one tiled window lives on the desktop, absolutely no gaps
workspace = w[tv1], gapsout:0, gapsin:0
windowrule {
    name = no-gaps-if-one-tiled-window
    match:workspace = w[tv1]
    border_size = 0
    rounding = 0
}

# If only one floating window lives on the desktop, absolutely no gaps
workspace = f[1], gapsout:0, gapsin:0
windowrule {
    name = no-gaps-if-fullscreen
    match:workspace = f[1]
    border_size = 0
    rounding = 0
}

# Ignore maximize requests from all apps. You'll probably like this.
windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

